// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"

	"github.com/siderolabs/image-factory/api"
)

const generatedHeader = "<!-- Code generated by tools/openapi-docgen; DO NOT EDIT. -->\n"

const introduction = `## Authentication

This Enterprise capability is controlled by the Image Factory configuration.
When it is disabled, authenticated endpoints are public, and the download-token endpoints are not registered.
When it is enabled, endpoints marked as required accept credentials described in [Authentication](authentication.md).

A download token is accepted only where the access table says so.
An Auth0 token carrying the configured machine scope is limited to operations marked as allowed.
Ownership indicates whether the authenticated identity is checked against the schematic owner.

## Edition and feature availability

Operations marked as Enterprise require [Enterprise Image Factory](https://docs.siderolabs.com/talos/latest/learn-more/enterprise-image-factory).
When the corresponding plugin is unavailable, its route is not registered or the operation returns the documented error.
`

var (
	repeatedBlankLines = regexp.MustCompile(`\n{3,}`)
	sentenceBoundary   = regexp.MustCompile(`([.!?]) +`)
)

type documentedOperation struct {
	pathItem  *openapi3.PathItem
	operation *openapi3.Operation
	method    string
	path      string
	tagIndex  int
}

func main() {
	if err := run(context.Background(), os.Args[1:]); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
}

func run(ctx context.Context, args []string) error {
	if len(args) != 1 {
		return errors.New("usage: openapi-docgen <output.md>")
	}

	data, err := generateReference(ctx)
	if err != nil {
		return err
	}

	if err = writeAtomically(args[0], data); err != nil {
		return fmt.Errorf("write API reference: %w", err)
	}

	return nil
}

func generateReference(ctx context.Context) ([]byte, error) {
	document, err := api.Load(ctx)
	if err != nil {
		return nil, fmt.Errorf("load OpenAPI contract: %w", err)
	}

	var output bytes.Buffer
	output.WriteString(generatedHeader)
	output.WriteString("\n# API\n\n")
	output.WriteString(normalizeText(document.Info.Description))
	output.WriteString("\n\n")
	output.WriteString(introduction)

	operations, err := collectOperations(document)
	if err != nil {
		return nil, err
	}

	currentTag := ""
	for _, item := range operations {
		if item.operation.Tags[0] != currentTag {
			currentTag = item.operation.Tags[0]

			output.WriteString("\n## ")
			output.WriteString(currentTag)
			output.WriteString("\n\n")
			output.WriteString(tagDescription(document, currentTag))
			output.WriteString("\n")
		}

		renderOperation(&output, document, item)
	}

	renderSchemas(&output, document)

	return repeatedBlankLines.ReplaceAll(output.Bytes(), []byte("\n\n")), nil
}

func collectOperations(document *openapi3.T) ([]documentedOperation, error) {
	tagIndexes := make(map[string]int, len(document.Tags))
	for index, tag := range document.Tags {
		tagIndexes[tag.Name] = index
	}

	var operations []documentedOperation

	for path, pathItem := range document.Paths.Map() {
		for method, operation := range pathItem.Operations() {
			if len(operation.Tags) != 1 {
				return nil, fmt.Errorf("operation %s %s must have exactly one tag", method, path)
			}

			index, ok := tagIndexes[operation.Tags[0]]
			if !ok {
				return nil, fmt.Errorf("operation %s %s uses undeclared tag %q", method, path, operation.Tags[0])
			}

			operations = append(operations, documentedOperation{
				method: method, path: path, pathItem: pathItem, operation: operation, tagIndex: index,
			})
		}
	}

	sort.Slice(operations, func(i, j int) bool {
		left, right := operations[i], operations[j]
		if left.tagIndex != right.tagIndex {
			return left.tagIndex < right.tagIndex
		}

		if left.path != right.path {
			return left.path < right.path
		}

		leftRank, rightRank := methodRank(left.method), methodRank(right.method)
		if leftRank != rightRank {
			return leftRank < rightRank
		}

		return left.method < right.method
	})

	return operations, nil
}

func methodRank(method string) int {
	switch strings.ToUpper(method) {
	case http.MethodGet:
		return 0
	case http.MethodHead:
		return 1
	case http.MethodPost:
		return 2
	case http.MethodPut:
		return 3
	case http.MethodPatch:
		return 4
	case http.MethodDelete:
		return 5
	case http.MethodOptions:
		return 6
	case http.MethodTrace:
		return 7
	default:
		return 100
	}
}

func tagDescription(document *openapi3.T, name string) string {
	for _, tag := range document.Tags {
		if tag.Name == name {
			return normalizeText(tag.Description)
		}
	}

	return ""
}

func renderOperation(output *bytes.Buffer, document *openapi3.T, item documentedOperation) {
	operation := item.operation
	fmt.Fprintf(output, "\n### `%s %s`\n\n", strings.ToUpper(item.method), item.path)
	fmt.Fprintf(output, "%s\n\n", proseText(operation.Summary))

	if isEnterprise(operation.Extensions) {
		output.WriteString("> [!NOTE]\n> Enterprise route.\n\n")
	}

	output.WriteString(proseText(operation.Description))
	output.WriteString("\n\n")

	if minimum, ok := operation.Extensions["x-image-factory-min-talos-version"].(string); ok {
		fmt.Fprintf(output, "Available for Talos **%s** and later.\n\n", minimum)
	}

	operationLabel := strings.ToUpper(item.method) + " " + item.path
	renderAccess(output, document, operation, operationLabel)
	renderParameters(output, item.pathItem.Parameters, operation.Parameters, operationLabel)
	renderRequestBody(output, operation.RequestBody, operationLabel)
	renderResponses(output, operation.Responses, operationLabel)
}

func renderAccess(output *bytes.Buffer, document *openapi3.T, operation *openapi3.Operation, operationLabel string) {
	security := document.Security
	if operation.Security != nil {
		security = *operation.Security
	}

	authentication := "public"
	downloadToken := "not applicable"
	machineScope := "not applicable"
	ownership := "not applicable"
	ownershipDescription := ""

	if len(security) > 0 {
		authentication = "required"
		downloadToken = "not accepted"

		for _, requirement := range security {
			if _, ok := requirement["downloadToken"]; ok {
				downloadToken = "accepted"
			}
		}

		if raw, ok := operation.Extensions["x-image-factory-access"]; ok {
			if access, valid := raw.(map[string]any); valid {
				machineScope = extensionString(access, "machineScope", machineScope)
				ownership = extensionString(access, "ownership", ownership)
				ownershipDescription = extensionString(access, "ownershipDescription", ownershipDescription)
			}
		}
	}

	fmt.Fprintf(output, "#### Access for `%s`\n\n", operationLabel)
	output.WriteString("|Auth|`?token=`|Machine scope|Ownership|\n")
	output.WriteString("|---|---|---|---|\n")
	fmt.Fprintf(output, "|%s|%s|%s|%s|\n\n", authentication, downloadToken, machineScope, ownership)

	if ownershipDescription != "" {
		fmt.Fprintf(output, "Ownership: %s\n\n", proseText(ownershipDescription))
	}
}

func extensionString(values map[string]any, key, fallback string) string {
	if value, ok := values[key].(string); ok {
		return value
	}

	return fallback
}

func isEnterprise(extensions map[string]any) bool {
	enterprise, ok := extensions["x-enterprise"].(bool)

	return ok && enterprise
}

func markEnterprise(description string, extensions map[string]any) string {
	if !isEnterprise(extensions) {
		return description
	}

	if description == "" {
		return "**Enterprise.**"
	}

	return "**Enterprise.** " + description
}

func renderParameters(output *bytes.Buffer, pathParameters, operationParameters openapi3.Parameters, operationLabel string) {
	parameters := mergeParameters(pathParameters, operationParameters)
	if len(parameters) == 0 {
		return
	}

	details := make([]*openapi3.Parameter, 0)

	fmt.Fprintf(output, "#### Parameters for `%s`\n\n", operationLabel)
	output.WriteString("|Name|In|Required|Type|Description|\n")
	output.WriteString("|---|---|---|---|---|\n")

	for _, reference := range parameters {
		if reference == nil || reference.Value == nil {
			continue
		}

		parameter := reference.Value

		required := "no"
		if parameter.Required {
			required = "yes"
		}

		description := normalizeText(parameter.Description)
		if strings.Contains(description, "\n") {
			details = append(details, parameter)

			description, _, _ = strings.Cut(description, "\n")
		}

		description = normalizeCell(description)
		if parameter.Example != nil {
			description = appendSentence(description, "Example: `"+normalizeCell(fmt.Sprint(parameter.Example))+"`.")
		}

		description = markEnterprise(description, parameter.Extensions)

		fmt.Fprintf(
			output, "|`%s`|%s|%s|%s|%s|\n",
			normalizeCell(parameter.Name), normalizeCell(parameter.In), required,
			schemaType(parameter.Schema), description,
		)
	}

	output.WriteString("\n")

	for _, detail := range details {
		fmt.Fprintf(output, "**Supported values for `%s`**\n\n%s\n\n", normalizeCell(detail.Name), markEnterprise(proseText(detail.Description), detail.Extensions))
	}
}

func mergeParameters(pathParameters, operationParameters openapi3.Parameters) openapi3.Parameters {
	parameters := append(openapi3.Parameters{}, pathParameters...)
	indexes := make(map[string]int, len(parameters))

	for index, parameter := range parameters {
		indexes[parameterKey(parameter)] = index
	}

	for _, parameter := range operationParameters {
		key := parameterKey(parameter)
		if index, ok := indexes[key]; ok {
			parameters[index] = parameter

			continue
		}

		indexes[key] = len(parameters)
		parameters = append(parameters, parameter)
	}

	return parameters
}

func parameterKey(parameter *openapi3.ParameterRef) string {
	if parameter == nil {
		return "<nil>"
	}

	if parameter.Value == nil {
		return parameter.Ref
	}

	return parameter.Value.In + "\x00" + parameter.Value.Name
}

func renderRequestBody(output *bytes.Buffer, reference *openapi3.RequestBodyRef, operationLabel string) {
	if reference == nil || reference.Value == nil {
		return
	}

	body := reference.Value

	fmt.Fprintf(output, "#### Request body for `%s`\n\n", operationLabel)

	if body.Description != "" {
		output.WriteString(proseText(body.Description))
		output.WriteString("\n\n")
	}

	output.WriteString("|Content type|Schema|Required|\n")
	output.WriteString("|---|---|---|\n")

	contentTypes := sortedKeys(body.Content)
	for _, contentType := range contentTypes {
		required := "no"
		if body.Required {
			required = "yes"
		}

		fmt.Fprintf(output, "|`%s`|%s|%s|\n", normalizeCell(contentType), schemaType(body.Content[contentType].Schema), required)
	}

	output.WriteString("\n")
}

func renderResponses(output *bytes.Buffer, responses *openapi3.Responses, operationLabel string) {
	if responses == nil {
		return
	}

	fmt.Fprintf(output, "#### Responses for `%s`\n\n", operationLabel)
	output.WriteString("|Status|Description|Content types|Schemas|Headers|\n")
	output.WriteString("|---|---|---|---|---|\n")

	values := responses.Map()
	statuses := sortedKeys(values)
	sort.SliceStable(statuses, func(i, j int) bool {
		if statuses[i] == "default" {
			return false
		}

		if statuses[j] == "default" {
			return true
		}

		return statuses[i] < statuses[j]
	})

	for _, status := range statuses {
		reference := values[status]
		if reference == nil || reference.Value == nil {
			continue
		}

		response := reference.Value

		contentTypes := make([]string, 0, len(response.Content))

		schemas := make([]string, 0, len(response.Content))
		for _, contentType := range sortedKeys(response.Content) {
			contentTypes = append(contentTypes, "`"+normalizeCell(contentType)+"`")
			schemas = append(schemas, schemaType(response.Content[contentType].Schema))
		}

		headers := make([]string, 0, len(response.Headers))
		for _, header := range sortedKeys(response.Headers) {
			headers = append(headers, "`"+normalizeCell(header)+"`")
		}

		description := ""
		if response.Description != nil {
			description = normalizeCell(*response.Description)
		}

		description = markEnterprise(description, response.Extensions)
		fmt.Fprintf(output, "|`%s`|%s|%s|%s|%s|\n", status, description, strings.Join(contentTypes, ", "), strings.Join(schemas, ", "), strings.Join(headers, ", "))
	}

	output.WriteString("\n")
}

func renderSchemas(output *bytes.Buffer, document *openapi3.T) {
	output.WriteString("\n## Schemas\n\n")
	output.WriteString("Reusable request and response schemas from the OpenAPI contract.\n")

	for _, name := range sortedKeys(document.Components.Schemas) {
		reference := document.Components.Schemas[name]
		if reference == nil || reference.Value == nil {
			continue
		}

		schema := reference.Value

		fmt.Fprintf(output, "\n### `%s`\n\n", name)

		if isEnterprise(schema.Extensions) {
			output.WriteString("> [!NOTE]\n> Enterprise component.\n\n")
		}

		if schema.Description != "" {
			output.WriteString(proseText(schema.Description))
			output.WriteString("\n\n")
		}

		fmt.Fprintf(output, "Type: %s\n\n", schemaType(&openapi3.SchemaRef{Value: schema}))

		if len(schema.Properties) > 0 {
			output.WriteString("|Property|Type|Required|Description|\n")
			output.WriteString("|---|---|---|---|\n")

			required := make(map[string]struct{}, len(schema.Required))
			for _, property := range schema.Required {
				required[property] = struct{}{}
			}

			for _, property := range sortedKeys(schema.Properties) {
				propertyReference := schema.Properties[property]

				isRequired := "no"
				if _, ok := required[property]; ok {
					isRequired = "yes"
				}

				description := ""
				if propertyReference != nil && propertyReference.Value != nil {
					description = schemaDescription(propertyReference.Value)
					description = markEnterprise(description, propertyReference.Value.Extensions)
				}

				fmt.Fprintf(output, "|`%s`|%s|%s|%s|\n", normalizeCell(property), schemaType(propertyReference), isRequired, description)
			}

			output.WriteString("\n")
		}

		if len(schema.Examples) > 0 {
			output.WriteString("Example:\n\n```json\n")

			data, err := json.MarshalIndent(schema.Examples[0], "", "  ")
			if err == nil {
				output.Write(data)
			}

			output.WriteString("\n```\n")
		}
	}
}

func schemaDescription(schema *openapi3.Schema) string {
	description := normalizeCell(schema.Description)
	if len(schema.Enum) > 0 {
		values := make([]string, 0, len(schema.Enum))
		for _, value := range schema.Enum {
			values = append(values, "`"+normalizeCell(fmt.Sprint(value))+"`")
		}

		description = appendSentence(description, "Allowed values: "+strings.Join(values, ", ")+".")
	}

	if schema.Pattern != "" {
		description = appendSentence(description, "Pattern: `"+normalizeCell(schema.Pattern)+"`.")
	}

	if schema.Default != nil {
		description = appendSentence(description, "Default: `"+normalizeCell(fmt.Sprint(schema.Default))+"`.")
	}

	return description
}

func schemaType(reference *openapi3.SchemaRef) string {
	if reference == nil {
		return "any"
	}

	if name := referencedName(reference.Ref); name != "" {
		return "`" + name + "`"
	}

	if reference.Value == nil {
		return "any"
	}

	schema := reference.Value
	if len(schema.OneOf) > 0 {
		values := make([]string, 0, len(schema.OneOf))
		for _, candidate := range schema.OneOf {
			if candidate != nil && candidate.Value != nil && candidate.Value.Title != "" {
				values = append(values, candidate.Value.Title)

				continue
			}

			values = append(values, schemaType(candidate))
		}

		return strings.Join(values, " or ")
	}

	if schema.Type == nil || len(*schema.Type) == 0 {
		return "any"
	}

	types := append([]string{}, (*schema.Type)...)
	if len(types) == 1 && types[0] == "array" {
		return "array<" + schemaType(schema.Items) + ">"
	}

	result := strings.Join(types, " or ")
	if schema.Format != "" {
		result += " (`" + schema.Format + "`)"
	}

	return result
}

func referencedName(reference string) string {
	if reference == "" {
		return ""
	}

	if index := strings.LastIndex(reference, "/"); index >= 0 && index+1 < len(reference) {
		return reference[index+1:]
	}

	return ""
}

func appendSentence(description, sentence string) string {
	if description == "" {
		return sentence
	}

	return strings.TrimSuffix(description, ".") + "; " + sentence
}

func normalizeText(value string) string {
	return strings.TrimSpace(strings.ReplaceAll(value, "\r\n", "\n"))
}

func proseText(value string) string {
	return sentenceBoundary.ReplaceAllString(normalizeText(value), "$1\n")
}

func normalizeCell(value string) string {
	value = normalizeText(value)
	value = strings.Join(strings.Fields(value), " ")
	value = strings.ReplaceAll(value, ". ", "; ")
	value = strings.ReplaceAll(value, "|", "\\|")

	return value
}

func sortedKeys[Map ~map[string]Value, Value any](values Map) []string {
	keys := make([]string, 0, len(values))
	for key := range values {
		keys = append(keys, key)
	}

	sort.Strings(keys)

	return keys
}

func writeAtomically(destination string, data []byte) error {
	directory := filepath.Dir(destination)
	if err := os.MkdirAll(directory, 0o755); err != nil {
		return fmt.Errorf("create output directory: %w", err)
	}

	file, err := os.CreateTemp(directory, ".api-reference-*.md")
	if err != nil {
		return fmt.Errorf("create temporary file: %w", err)
	}

	temporary := file.Name()
	defer os.Remove(temporary) //nolint:errcheck

	if _, err = file.Write(data); err != nil {
		file.Close() //nolint:errcheck

		return fmt.Errorf("write temporary file: %w", err)
	}

	if err = file.Chmod(0o644); err != nil {
		file.Close() //nolint:errcheck

		return fmt.Errorf("set output permissions: %w", err)
	}

	if err = file.Close(); err != nil {
		return fmt.Errorf("close temporary file: %w", err)
	}

	if err = os.Rename(temporary, destination); err != nil {
		return fmt.Errorf("replace output: %w", err)
	}

	return nil
}
