// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at http://mozilla.org/MPL/2.0/.

package main

import (
	"os"
	"strings"
	"testing"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func TestGenerateReference(t *testing.T) {
	t.Parallel()

	first, err := generateReference(t.Context())
	require.NoError(t, err)
	second, err := generateReference(t.Context())
	require.NoError(t, err)

	assert.Equal(t, first, second)

	output := string(first)
	assert.True(t, strings.HasPrefix(output, "<!-- Code generated by tools/openapi-docgen; DO NOT EDIT. -->\n\n# API\n"))
	assert.Contains(t, output, "## Enterprise Frontend API")
	assert.Contains(t, output, "### `GET /spdx/{schematic}/{version}/{arch}`\n\nGet a merged SPDX document\n\n> [!NOTE]\n> Enterprise route.")
	assert.Contains(t, output, "|required|not accepted|denied|enforced|")
	assert.Contains(t, output, "|required|not accepted|allowed|conditional|")
	assert.Contains(t, output, "Ownership: Enforced for generated installer repositories")
	assert.Contains(t, output, "## Frontend API")
	assert.Contains(t, output, "### `POST /schematics`")
	assert.Contains(t, output, "## Schemas")
	assert.Contains(t, output, "### `Schematic`")
	assert.Contains(t, output, "|`200`|Talos version strings with leading `v` prefixes.|`application/json`|`VersionList`|")
	assert.Contains(t, output, "### `VersionList`\n\nTalos Linux versions available for image generation.\n\nType: array<string>")
	assert.Contains(t, output, "### `DownloadToken`\n\n> [!NOTE]\n> Enterprise component.")
	assert.Contains(t, output, "|`token`|query|no|string|**Enterprise.**")
	assert.Contains(t, output, "|`owner`|string|no|**Enterprise.**")
	assert.Contains(t, output, "|`extraKernelArgs`|array<string>|no|Additional arguments appended to the kernel command line.")
	assert.Contains(t, output, "`<platform>-<arch>[-secureboot].iso`")
	assert.Contains(t, output, "`<platform>-<arch>[-secureboot].<disk-format>[.<compression>]`")
	assert.Contains(t, output, "Disk formats are `raw`, `qcow2`, `vhd`, and `ova`.")
	assert.Contains(t, output, "Compression suffixes are `tar.gz`, `gz`, `xz`, and `zst`.")
	assert.Contains(t, output, "`.sha256`, `.sha512`, or `.sigstore.json`")
	assert.NotContains(t, output, ".sha256sum")
}

func TestMethodRankCoversOpenAPIMethods(t *testing.T) {
	t.Parallel()

	methods := []string{"get", "head", "post", "put", "patch", "delete", "options", "trace"}
	seen := map[int]struct{}{}

	for _, method := range methods {
		rank := methodRank(method)
		_, duplicate := seen[rank]
		assert.False(t, duplicate, "%s has duplicate method rank %d", method, rank)
		seen[rank] = struct{}{}
	}
}

func TestMergeParametersUsesOperationOverride(t *testing.T) {
	t.Parallel()

	pathParameter := &openapi3.ParameterRef{Value: &openapi3.Parameter{Name: "id", In: openapi3.ParameterInPath, Description: "path item"}}
	operationParameter := &openapi3.ParameterRef{Value: &openapi3.Parameter{Name: "id", In: openapi3.ParameterInPath, Description: "operation"}}

	parameters := mergeParameters(openapi3.Parameters{pathParameter}, openapi3.Parameters{operationParameter})
	require.Len(t, parameters, 1)
	assert.Equal(t, "operation", parameters[0].Value.Description)
}

func TestGeneratedReferenceIsCurrent(t *testing.T) {
	t.Parallel()

	generated, err := generateReference(t.Context())
	require.NoError(t, err)
	committed, err := os.ReadFile("../../docs/api.md")
	require.NoError(t, err)

	assert.Equal(t, string(generated), string(committed), "run `go run ./tools/openapi-docgen docs/api.md`")
}
